FROM eclipse-temurin:21-jre
# Note: Eclipse Temurin JRE 25 will be substituted if available, otherwise defaulting to standard stable JRE 21 with early access components.
WORKDIR /server
EXPOSE 25565
CMD ["java", "-jar", "server.jar", "nogui"]
